# Data Representation (Part 1)

This is an accompanying notebook for the Data Representation lecture

In [ ]:
# @title Import pandas library
import pandas as pd

In [ ]:
# @title Create and print DataFrame

# Manually create DataFrame
example_df = pd.DataFrame({
    "Name": ["Mark", "Jane", "Bob", "Maria", "Alice", "Seth"],
    "Age": [20, 22, 21, 20, 19, 17],
    "Sex": ["M", "F", "M", "F", "F", "M"]
})

# Print DataFrame content
example_df

    Name  Age Sex
0   Mark   20   M
1   Jane   22   F
2    Bob   21   M
3  Maria   20   F
4  Alice   19   F
5   Seth   17   M

In [ ]:
# @title Create and print Series

# Manually create Series
example_series = pd.Series(["Mark", "Jane", "Bob", "Maria", "Alice", "Seth"], name="Name")

# Print Series content
example_series

0     Mark
1     Jane
2      Bob
3    Maria
4    Alice
5     Seth
Name: Name, dtype: object

In [ ]:
# @title A DataFrame is a combination of multiple Series

# Manually create Series
series_1 = pd.Series(["Mark", "Jane", "Bob", "Maria", "Alice", "Seth"])
series_2 = pd.Series([20, 22, 21, 20, 19, 17])
series_3 = pd.Series(["M", "F", "M", "F", "F", "M"])

# Manually create DataFrame from the Series
df = pd.DataFrame({"Name": series_1, "Age": series_2, "Sex":  series_3})

# Print DataFrame content
df

    Name  Age Sex
0   Mark   20   M
1   Jane   22   F
2    Bob   21   M
3  Maria   20   F
4  Alice   19   F
5   Seth   17   M

In [ ]:
# @title Scalar Operations

# Manually create Series
age_series = pd.Series([20, 22, 21, 20, 19, 17], name="Age")

# Do scalar operation and store results in another variable
results_series = age_series > 20

# Print Series content
results_series

0    False
1     True
2     True
3    False
4    False
5    False
Name: Age, dtype: bool

In [ ]:
# @title Series to Series Operations

# Manually create Series
dist_series = pd.Series([10, 20, 30, 10, 100, 200, 300], name="Distance")
time_series = pd.Series([20, 10, 30, 100, 10], name="Time")

# Do series to series operation and store results in another variable
results_series = dist_series / time_series

# Print Series content
results_series

0     0.5
1     2.0
2     1.0
3     0.1
4    10.0
5     NaN
6     NaN
dtype: float64

In [ ]:
# @title View Documentation
?pd.read_csv